### PR TITLE
Fix nil indexing error

### PR DESCRIPTION
**Pull request by pseudoname23**
Fixes the following error I was encountering when I tried to create a world. 
__pyalienlife__/control.lua:215: attempt to index global 'created_items' (a nil value)

I'm sorry if I made any errors with this PR, I have very little experience with Lua.

### CODE REVIEW

**Comment by ShadowGlass0** [comment]
Already fixed

**Comment by pseudoname23** [comment]
I just tested it, it's not fixed. I can submit a formal bug report for this if you want, or open another PR for the code I wrote to fix it.

**Comment by ShadowGlass0** [comment]
It's not released yet, but it's fixed on Github

**Comment by pseudoname23** [comment]
Oh, that makes sense. Thanks for the clarification

**Pull request closed without merging**
