### PR TITLE
 Global Caravan handling GUI

### PR DESCRIPTION
**Pull request by TheGoesen**
Hello.
I am currently working on some Gui additions to make life with caravans more tolerable. My first instinct was to just dump everything into a window, like the train overview or the universe explorer. 
image

I quickly realized that that didnt actually address the most helpful thing needed, which I would describe as: given a full outpost, where is the caravan stuck thats supposed to empty it? So lets make a list when you click on an outpost, that gives you all caravans connected to it
image
That seems like a start...
So open questions.. what information can we actually put in the UI, how should it look like? The status light code is nice, but there is currently no light code for: 'caravan is just wandering around and not automated'... maybe turn this state to yellow?
Caravans could be connected to cargo wagon, so how handle cargo wagon to caravan? I like the idea of maybe adding something like the logistic button for caravans, but dont know if technically possible ..
image
 Do you have suggestions?

### CODE REVIEW

**Comment by notnotmelon** [comment]
That's really cool. But we will need a button next to each caravan that directly opens the GUI. Also, what is the purpose of "key" column?

**Comment by notnotmelon** [comment]
What is the effect of "Caravan Organizer" hotkey?

**Comment by TheGoesen** [comment]
So currently: if you click on the "key" column it opens the caravan GUI (So Maybe it should look like an button?). It will definitely not print some integers in a more developed version

 However if you have a caravan open, you can also transfer items to and from the inventory of the caravan, even if its out of reach. 
That is 'cheating' from a vanilla standpoint, from a py standpoint you might argue that forcing the player to manually walk to the caravan is not a  required game mechanic and manually teleporting some items is not an huge issue....

The effect of the caravan organizer hotkey is that it opens a list every caravan, not just the ones connected to the selected outpost.
(See screenshot 1) It initially seemed to me a good idea to build a global UI, something that is very similar to the global train UI. 
However-> the caravans dont have names, the outpost dont have names, so how do you identify anything in global Ui???

**Comment by TheGoesen** [comment]
So maybe ditching the global UI is in option, but it might still be useful for routine checks to see if you accidentely broke any of your caravans somewhere (state starving or state 'not automated')

**Comment by notnotmelon** [comment]
I have a solution for the inventory teleports. Once the PR is merged I will implement it.

**Comment by TheGoesen** [comment]
Ok that took a while to stop it from misbehaving...
The GUI looks like shit, I am not a factorio style wizard, feel free to change things around... So now we have a gui for things that are 'connected' to a caravan (caravan outpost), that shows all caravans that have a schedule there. 
image
And the global caravan organizer thing is also there 
image

**Comment by TheGoesen** [comment]
Oh and i have changed the text from 'Goto Caravan' to 'Open Caravan' but the screenshots are still wrong. Tired....

**Comment by notnotmelon** [comment]
Wow, great effort on this. I believe this is the most high-effort PR we've had. I'll add some commits on your branch to improve the GUI style.

**Comment by kingarthur91** [comment]
is this done or what?

**Comment by TheGoesen** [comment]
from my perspective this can be merged, @notnotmelon do you want to do more refactoring, should i make changes?

**Comment by notnotmelon** [comment]
This needs more work on the graphics/styling side. It's one of my top priorities!

**Comment by notnotmelon** [comment]
Merged and uploaded to the mod portal. Thanks again!

**Comment by notnotmelon** [comment]
Here is the final version after my styling:

https://imgur.com/a/JR8HO42

**Comment by TheGoesen** [comment]
Poggies very cool thanks :) need to boot the game up again ;)

**Pull request merged**
